// demo package simulating a realtime generation and processing.
// Start the example from your terminal and type a letter + enter.
package main

import (
	"fmt"
	"log"
	"os"
	"os/signal"
	"time"

	"github.com/go-audio/audio"
	"github.com/go-audio/generator"
	"github.com/go-audio/transforms"
	"github.com/gordonklaus/portaudio"
	"github.com/ojrac/opensimplex-go"
)

func main() {

	// Create a buffer to store all of the audio data
	// ... more?
	bufferSize := 512
	buf := &audio.FloatBuffer{
		Data:   make([]float64, bufferSize),
		Format: audio.FormatMono44100,
	}

	// Set the base frequencies.
	// Eventually we may have many frequencies that overlap to create more complex sounds
	baseFrequency := 70.0
	currentNote := baseFrequency

	// Noise Generator
	simplex := opensimplex.New(0)

	// Create the oscillator
	osc := generator.NewOsc(generator.WaveSine, currentNote, buf.Format.SampleRate)
	osc.Amplitude = 1

	// I dont know what this is... yet
	sig := make(chan os.Signal, 1)
	signal.Notify(sig, os.Interrupt, os.Kill)

	// Some other metadata
	// Gain control is effectivly used to control the volume
	// currentVol is the amplitude of the wave generated by the oscilator
	gainControl := 0.0
	currentVol := osc.Amplitude

	// This is a GoRoutine
	// It basically runs in a seperate thread which is nice because then we
	// can just update the OSCILLATOR in parallel
	go func() {

		// This is what the noise function uses to figure out the variance value it's going to produce
		step := 0.0

		for {

			// These are the noise variance generators.
			// Simplex noise generates an organic feeling distortion that is applied to the defined base tone
			// This allows for a biot of variety in our sound output.
			step += 0.000005
			variance := 5.0 // In Hz
			finalOffset := simplex.Eval2(step, 0.0)

			currentNote = baseFrequency + (variance * finalOffset) // Current note is defined early on. It holds the current frequency of the sine wave being produced
			osc.SetFreq(currentNote)                               // Set the oscilators frequency

			time.Sleep(5 * time.Millisecond) // Wait 5 miliseconds between each update to reduce the load on the CPU
		}
	}()

	// Audio output

	// Initialize PortAudio
	// PortAudio is a CrossPlatform library that is used to work with Audio I/O.
	// Since working directly with the underlying systems is a PAIN IN THE ASS, PortAudio makes this easier.
	portaudio.Initialize()

	// A defer statement defers the execution of a function until the surrounding function returns.
	// Wait until the function returns to terminate PortAudio
	defer portaudio.Terminate()

	// Create a buffer that matches the size of our original audio buffer.
	// ...
	out := make([]float32, bufferSize)

	// Opens a I/O stream to the DEFAULT AUDIO DEVICE(S) on the system.
	// Alternativly, you could use the normal OpenStream where you specify an audio device to use.
	// Frames Per Buffer should match the length of our output buffer that we created just a moment ago.
	// The final argument is a refrence address to the output buffer
	stream, err := portaudio.OpenDefaultStream(0, 1, 44100, len(out), &out)

	// Oh, and if something failed to open then just die tbh...
	if err != nil {
		log.Fatal(err)
	}

	// A defer statement defers the execution of a function until the surrounding function returns.
	// Wait until the function returns to close the stream
	defer stream.Close()

	// Start the stream for audio processing
	// If stream.Start() returns anything other than nil than there was an error that occured
	if err := stream.Start(); err != nil {
		log.Fatal(err)
	}

	// Wait till the function returns to stop the stream
	defer stream.Stop()

	// Loop forever in the main thread
	for {

		// Generate the data and put it in our buf
		if err := osc.Fill(buf); err != nil {
			log.Printf("error filling up the buffer")
		}

		// apply vol control if needed (applied as a transform instead of a control
		// on the osc)
		if gainControl != 0 {
			currentVol += gainControl
			if currentVol < 0.1 {
				currentVol = 0
			}
			if currentVol > 6 {
				currentVol = 6
			}
			fmt.Printf("new vol %f.2", currentVol)
			gainControl = 0
		}
		transforms.Gain(buf, currentVol)

		f64ToF32Copy(out, buf.Data)

		// write to the stream
		if err := stream.Write(); err != nil {
			log.Printf("error writing to stream : %v\n", err)
		}
		select {
		case <-sig:
			fmt.Println("\tCiao!")
			return
		default:
		}
	}

}

// portaudio doesn't support float64 so we need to copy our data over to the
// destination buffer.
func f64ToF32Copy(dst []float32, src []float64) {
	for i := range src {
		dst[i] = float32(src[i])
	}
}
